[package]
name = "speed-typing"
version = "1.0.0"
edition = "2024"

description = "A terminal-based speed typing test"
authors = ["Danylo Mamchur"]
repository = "https://github.com/DanieloM83/Speed-Typing"
license = "MIT"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
indexmap = "2.14.1"
rand = "0.10.2"
ratatui = "0.30.2"
unicode-width = "0.2.2"
